name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |
        set -e
        docker buildx create --use
        docker_tag=${{ secrets.DOCKERHUB_USERNAME }}/pulsar-beam
        cache_docker_tag=${{ env.REGISTRY }}/${{ github.repository }}
        docker buildx build . \
          --pull \
          --push \
          --cache-from type=registry,ref=${cache_docker_tag}:cache \
          --cache-to type=registry,ref=${cache_docker_tag}:cache \
          --tag ${docker_tag}
